server:
  port: 8099
spring:
  security: # 配置登录用户名和密码
    user:
      name: admin
      password: 123123
  boot:  # 不显示 admin-server (自身)的监控信息
    admin:
      discovery:
        ignored-services: ${spring.application.name}
